"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./translations/"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [{
    "source": "/en-GB/**/*.json",
    "translation": "/%two_letters_code%/**/%original_file_name%",
    "type": "json",
    "excluded_target_languages": [
        "nb",
        "sr"
    ],
    "languages_mapping": {
        "two_letters_code": {
            "ar": "ar-SA",
            "bg": "bg-BG",
            "bs": "bs-BA",
            "ca": "ca-ES",
            "cs": "cs-CZ",
            "da": "da-DK",
            "de": "de-DE",
            "el": "el-GR",
            "fi": "fi-FI",
            "fr": "fr-FR",
            "he": "he-IL",
            "hi": "hi-IN",
            "hr": "hr-HR",
            "hu": "hu-HU",
            "id": "id-ID",
            "it": "it-IT",
            "ja": "ja-JP",
            "ko": "ko-KR",
            "lt": "lt-LT",
            "lv": "lv-LV",
            "nl": "nl-NL",
            "no": "nb-NO",
            "pl": "pl-PL",
            "pt": "pt-PT",
            "ro": "ro-RO",
            "ru": "ru-RU",
            "sk": "sk-SK",
            "sl": "sl-SI",
#            "sr": "sr-RS", # ToDo: Re-enable; sr-RS (Serbian in Serbia) will be used for the cyrillic version, while sr-CS (Serbian in Serbia and Montenegro) will be used for the latin version
            "th": "th-TH",
            "tr": "tr-TR",
            "uk": "uk-UA",
            "vi": "vi-VN"
        }
    }
}, {
    "source": "/en-GB/**/*.json",
    "translation": "/%locale%/**/%original_file_name%",
    "type": "json",
    "excluded_target_languages": [
        "nb",
        "sr"
    ],
    "languages_mapping": {
        "two_letters_code": {
            "ar": "ar-SA",
            "bg": "bg-BG",
            "bs": "bs-BA",
            "ca": "ca-ES",
            "cs": "cs-CZ",
            "da": "da-DK",
            "de": "de-DE",
            "el": "el-GR",
            "fi": "fi-FI",
            "fr": "fr-FR",
            "he": "he-IL",
            "hi": "hi-IN",
            "hr": "hr-HR",
            "hu": "hu-HU",
            "id": "id-ID",
            "it": "it-IT",
            "ja": "ja-JP",
            "ko": "ko-KR",
            "lt": "lt-LT",
            "lv": "lv-LV",
            "nl": "nl-NL",
            "no": "nb-NO",
            "pl": "pl-PL",
            "pt": "pt-PT",
            "ro": "ro-RO",
            "ru": "ru-RU",
            "sk": "sk-SK",
            "sl": "sl-SI",
#            "sr": "sr-RS", # ToDo: Re-enable; sr-RS (Serbian in Serbia) will be used for the cyrillic version, while sr-CS (Serbian in Serbia and Montenegro) will be used for the latin version
            "th": "th-TH",
            "tr": "tr-TR",
            "uk": "uk-UA",
            "vi": "vi-VN"
        }
    }
}]
