"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./translations/"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files: [{
  #    "source": "/sources/en-GB/**/*.json",
  #    "translation": "/translations/%locale%/**/%original_file_name%",
  #    "type": "json",
  #    "escape_quotes": 2,
  #    "escape_special_characters": 0
  #}, {
  ## Single File Test ##
    "source": "/en-GB/Platform/Administration/administration.json",
    "translation": "/%locale%/Platform/Administration/%original_file_name%",
    "type": "json"
}]
