"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "./translations/"
"base_url": "https://api.crowdin.com"

files: [{
    "source": "/en-GB/**/*.json",
    "translation": "/%locale%/**/%original_file_name%",
    "type": "json",
    "update_option": "update_as_unapproved",
    "translation_replace": {
        "no-NO": "nn-NO"
    },
    "languages_mapping": {
        "locale": {
            "sr-CS": "sr-RS"
        }
    }
}, {
    "source": "/en-GB/**/*.json",
    "translation": "/%two_letters_code%/**/%original_file_name%",
    "type": "json",
    "update_option": "update_as_unapproved",
    "translation_replace": {
        "de": "de-DE"
    },
    "languages_mapping": {
        "two_letters_code": {
            "ar": "ar-SA",
            "bg": "bg-BG",
            "bs": "bs-BA",
            "ca": "ca-ES",
            "cs": "cs-CZ",
            "da": "da-DK",
            "el": "el-GR",
            "fi": "fi-FI",
            "fr": "fr-FR",
            "he": "he-IL",
            "hi": "hi-IN",
            "hr": "hr-HR",
            "hu": "hu-HU",
            "id": "id-ID",
            "it": "it-IT",
            "ja": "ja-JP",
            "ko": "ko-KR",
            "lt": "lt-LT",
            "lv": "lv-LV",
            "nl": "nl-NL",
            "pl": "pl-PL",
            "pt": "pt-PT",
            "ro": "ro-RO",
            "ru": "ru-RU",
            "sk": "sk-SK",
            "sl": "sl-SI",
            "th": "th-TH",
            "tr": "tr-TR",
            "uk": "uk-UA",
            "vi": "vi-VN"
        }
    }
}]
