project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: ./translations
base_url: https://api.crowdin.com

files: [{
  "source": "/en-GB/**/*.json",
  "translation": "/%locale%/**/%original_file_name%",
  "type": "json",
  "update_option": "update_as_unapproved",
  "translation_replace": {
    "no-NO": "nn-NO"
  },
  "languages_mapping": {
    "locale": {
      "sr-CS": "sr-RS"
    }
  }
}, {
  "source": "/en-GB/**/*.json",
  "translation": "/%two_letters_code%/**/%original_file_name%",
  "type": "json",
  "update_option": "update_as_unapproved",
  "languages_mapping": {
    "two_letters_code": {
      "en-GB": "en",
      "hy-AM": "hy",
      "pt-PT": "pt",
      "sr-CS": "sr",
      "es-ES": "es",
      "sv-SE": "sv"
    }
  }
}]