issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopware/translations:.*
claim_pattern:
  workflow_ref: shopware/translations/.github/workflows/crowdin-download.yml@refs/heads/feat/sync-crowdin-metadata-and-last-update-timestamps-in-download-workflow

permissions:
  contents: write
