name: "Crowdin Upload Action"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *' # Every day at 20:00 UTC

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare pre-fill en-US language files
        run:  PROJECT_ROOT="${GITHUB_WORKSPACE}" sh ./scripts/prepare-en-US.sh

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          import_eq_suggestions: true
          download_translations: false
          preserve_hierarchy: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
