name: "Crowdin Download Action"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Every day at 22:00 UTC

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'Crowdin translations'
          pull_request_body: 'Crowdin translations update'
          pull_request_base_branch_name: 'main'

  update-metadata:
    needs: crowdin-download
    runs-on: ubuntu-latest
    steps:
      - name: Checkout localization branch fresh
        uses: actions/checkout@v4
        with:
          ref: i18n_crowdin_translations
          fetch-depth: 0

      - name: Update meta data
        run: |
          set -euo pipefail

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch --no-tags --prune origin main
          git checkout -B i18n_crowdin_translations origin/i18n_crowdin_translations

          mapfile -t FILES < <(git diff --name-only --diff-filter=ACMRT origin/main...HEAD)
          echo "Changed files: ${#FILES[@]}"

          if (( ${#FILES[@]} > 0 )); then
            node scripts/update-metadata.mjs "${FILES[@]}"

            if ! git diff --quiet -- crowdin-metadata.json; then
              git add crowdin-metadata.json
              git commit -m "Update Crowdin metadata"
              git push origin HEAD:i18n_crowdin_translations
            else
              echo "Metadata unchanged, nothing to commit."
            fi
          else
            echo "No translation files changed vs main."
          fi
