name: Crowdin Download Action

on:
  workflow_dispatch:

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin_translations

          create_pull_request: true
          pull_request_title: 'New Crowdin translations'
          pull_request_body: 'New Crowdin pull request with translations'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
#      - name: Remove faulty languages # ToDo: Clearify how to handle nb (Norsk vs Bokmal), sr (Cyrillic vs Latin) and de (imported with wrong name)
#        run: |
#          rm -rf ./translations/nb
#          rm -rf ./translations/sr
#          rm -rf ./translations/de-DE
#          mv ./translations/de ./translations/de-DE
#
