name: "Crowdin Download Action"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *' # Every day at 22:00 UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: i18n_crowdin_translations

          create_pull_request: true
          pull_request_title: 'Crowdin translations'
          pull_request_body: 'Crowdin translations update'
          pull_request_base_branch_name: 'main'

      - name: Reset git permissions after Crowdin action
        run: |
          sudo chmod -R 755 .git/ || true
          sudo chown -R $(whoami):$(whoami) .git/ || true

      - name: Update meta data
        run: |
          set -e # Fail on error

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git fetch origin i18n_crowdin_translations || echo "Branch i18n_crowdin_translations does not exist yet"

          if git show-ref --verify --quiet refs/remotes/origin/i18n_crowdin_translations; then
            git checkout i18n_crowdin_translations
          else
            echo "Branch i18n_crowdin_translations not found, skipping metadata update"
            exit 0
          fi

          CHANGED_FILES=$(git diff --name-only origin/main HEAD | tr '\n' ' ')

          if [[ -n "$CHANGED_FILES" ]]; then
            node scripts/update-metadata.mjs "$CHANGED_FILES"

            if [[ -n $(git status --porcelain) ]]; then
              git add crowdin-metadata.json
              git commit -m "Update Crowdin metadata"
              git push --set-upstream origin i18n_crowdin_translationsh
            fi
          else
            echo "No translation files changed"
          fi
